/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "openarm/v1/messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(openarm_v1_Message, openarm_v1_Message, AUTO)


PB_BIND(openarm_v1_Heartbeat, openarm_v1_Heartbeat, AUTO)


PB_BIND(openarm_v1_Ack, openarm_v1_Ack, AUTO)


PB_BIND(openarm_v1_SetJointAngles, openarm_v1_SetJointAngles, AUTO)





