/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_OPENARM_V1_OPENARM_V1_MESSAGES_PB_H_INCLUDED
#define PB_OPENARM_V1_OPENARM_V1_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _openarm_v1_Status {
    openarm_v1_Status_STATUS_OK = 0,
    openarm_v1_Status_STATUS_INVALID = 1,
    openarm_v1_Status_STATUS_OUT_OF_RANGE = 2,
    openarm_v1_Status_STATUS_TIMEOUT = 3,
    openarm_v1_Status_STATUS_I2C_ERROR = 4,
    openarm_v1_Status_STATUS_EMERGENCY_STOP = 5
} openarm_v1_Status;

/* Struct definitions */
typedef struct _openarm_v1_Heartbeat {
    char dummy_field;
} openarm_v1_Heartbeat;

typedef struct _openarm_v1_Ack {
    uint32_t seq_ack;
    openarm_v1_Status status;
    pb_callback_t message;
} openarm_v1_Ack;

typedef struct _openarm_v1_SetJointAngles {
    float base_rad;
    float shoulder_rad;
    float elbow_rad;
} openarm_v1_SetJointAngles;

typedef struct _openarm_v1_Message { /* transport-agnostic envelope */
    uint32_t seq; /* monotonic sequence */
    uint64_t timestamp_ms; /* unix ms (optional) */
    pb_size_t which_payload;
    union {
        openarm_v1_Heartbeat heartbeat;
        openarm_v1_SetJointAngles set_joint_angles;
        openarm_v1_Ack ack;
    } payload;
} openarm_v1_Message;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _openarm_v1_Status_MIN openarm_v1_Status_STATUS_OK
#define _openarm_v1_Status_MAX openarm_v1_Status_STATUS_EMERGENCY_STOP
#define _openarm_v1_Status_ARRAYSIZE ((openarm_v1_Status)(openarm_v1_Status_STATUS_EMERGENCY_STOP+1))



#define openarm_v1_Ack_status_ENUMTYPE openarm_v1_Status



/* Initializer values for message structs */
#define openarm_v1_Message_init_default          {0, 0, 0, {openarm_v1_Heartbeat_init_default}}
#define openarm_v1_Heartbeat_init_default        {0}
#define openarm_v1_Ack_init_default              {0, _openarm_v1_Status_MIN, {{NULL}, NULL}}
#define openarm_v1_SetJointAngles_init_default   {0, 0, 0}
#define openarm_v1_Message_init_zero             {0, 0, 0, {openarm_v1_Heartbeat_init_zero}}
#define openarm_v1_Heartbeat_init_zero           {0}
#define openarm_v1_Ack_init_zero                 {0, _openarm_v1_Status_MIN, {{NULL}, NULL}}
#define openarm_v1_SetJointAngles_init_zero      {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define openarm_v1_Ack_seq_ack_tag               1
#define openarm_v1_Ack_status_tag                2
#define openarm_v1_Ack_message_tag               3
#define openarm_v1_SetJointAngles_base_rad_tag   1
#define openarm_v1_SetJointAngles_shoulder_rad_tag 2
#define openarm_v1_SetJointAngles_elbow_rad_tag  3
#define openarm_v1_Message_seq_tag               1
#define openarm_v1_Message_timestamp_ms_tag      2
#define openarm_v1_Message_heartbeat_tag         10
#define openarm_v1_Message_set_joint_angles_tag  11
#define openarm_v1_Message_ack_tag               12

/* Struct field encoding specification for nanopb */
#define openarm_v1_Message_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   seq,               1) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp_ms,      2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,heartbeat,payload.heartbeat),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_joint_angles,payload.set_joint_angles),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ack,payload.ack),  12)
#define openarm_v1_Message_CALLBACK NULL
#define openarm_v1_Message_DEFAULT NULL
#define openarm_v1_Message_payload_heartbeat_MSGTYPE openarm_v1_Heartbeat
#define openarm_v1_Message_payload_set_joint_angles_MSGTYPE openarm_v1_SetJointAngles
#define openarm_v1_Message_payload_ack_MSGTYPE openarm_v1_Ack

#define openarm_v1_Heartbeat_FIELDLIST(X, a) \

#define openarm_v1_Heartbeat_CALLBACK NULL
#define openarm_v1_Heartbeat_DEFAULT NULL

#define openarm_v1_Ack_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   seq_ack,           1) \
X(a, STATIC,   SINGULAR, UENUM,    status,            2) \
X(a, CALLBACK, SINGULAR, STRING,   message,           3)
#define openarm_v1_Ack_CALLBACK pb_default_field_callback
#define openarm_v1_Ack_DEFAULT NULL

#define openarm_v1_SetJointAngles_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    base_rad,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    shoulder_rad,      2) \
X(a, STATIC,   SINGULAR, FLOAT,    elbow_rad,         3)
#define openarm_v1_SetJointAngles_CALLBACK NULL
#define openarm_v1_SetJointAngles_DEFAULT NULL

extern const pb_msgdesc_t openarm_v1_Message_msg;
extern const pb_msgdesc_t openarm_v1_Heartbeat_msg;
extern const pb_msgdesc_t openarm_v1_Ack_msg;
extern const pb_msgdesc_t openarm_v1_SetJointAngles_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define openarm_v1_Message_fields &openarm_v1_Message_msg
#define openarm_v1_Heartbeat_fields &openarm_v1_Heartbeat_msg
#define openarm_v1_Ack_fields &openarm_v1_Ack_msg
#define openarm_v1_SetJointAngles_fields &openarm_v1_SetJointAngles_msg

/* Maximum encoded size of messages (where known) */
/* openarm_v1_Message_size depends on runtime parameters */
/* openarm_v1_Ack_size depends on runtime parameters */
#define OPENARM_V1_OPENARM_V1_MESSAGES_PB_H_MAX_SIZE openarm_v1_SetJointAngles_size
#define openarm_v1_Heartbeat_size                0
#define openarm_v1_SetJointAngles_size           15

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
