// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file openarm/v1/messages.proto (package openarm.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message as Message$1 } from "@bufbuild/protobuf";

/**
 * Describes the file openarm/v1/messages.proto.
 */
export const file_openarm_v1_messages: GenFile = /*@__PURE__*/
  fileDesc("ChlvcGVuYXJtL3YxL21lc3NhZ2VzLnByb3RvEgpvcGVuYXJtLnYxIrsBCgdNZXNzYWdlEgsKA3NlcRgBIAEoDRIUCgx0aW1lc3RhbXBfbXMYAiABKAQSKgoJaGVhcnRiZWF0GAogASgLMhUub3BlbmFybS52MS5IZWFydGJlYXRIABI2ChBzZXRfam9pbnRfYW5nbGVzGAsgASgLMhoub3BlbmFybS52MS5TZXRKb2ludEFuZ2xlc0gAEh4KA2FjaxgMIAEoCzIPLm9wZW5hcm0udjEuQWNrSABCCQoHcGF5bG9hZCILCglIZWFydGJlYXQiSwoDQWNrEg8KB3NlcV9hY2sYASABKA0SIgoGc3RhdHVzGAIgASgOMhIub3BlbmFybS52MS5TdGF0dXMSDwoHbWVzc2FnZRgDIAEoCSJLCg5TZXRKb2ludEFuZ2xlcxIQCghiYXNlX3JhZBgBIAEoAhIUCgxzaG91bGRlcl9yYWQYAiABKAISEQoJZWxib3dfcmFkGAMgASgCKokBCgZTdGF0dXMSDQoJU1RBVFVTX09LEAASEgoOU1RBVFVTX0lOVkFMSUQQARIXChNTVEFUVVNfT1VUX09GX1JBTkdFEAISEgoOU1RBVFVTX1RJTUVPVVQQAxIUChBTVEFUVVNfSTJDX0VSUk9SEAQSGQoVU1RBVFVTX0VNRVJHRU5DWV9TVE9QEAViBnByb3RvMw");

/**
 * transport-agnostic envelope
 *
 * @generated from message openarm.v1.Message
 */
export type Message = Message$1<"openarm.v1.Message"> & {
  /**
   * monotonic sequence
   *
   * @generated from field: uint32 seq = 1;
   */
  seq: number;

  /**
   * unix ms (optional)
   *
   * @generated from field: uint64 timestamp_ms = 2;
   */
  timestampMs: bigint;

  /**
   * extensible
   *
   * @generated from oneof openarm.v1.Message.payload
   */
  payload: {
    /**
     * @generated from field: openarm.v1.Heartbeat heartbeat = 10;
     */
    value: Heartbeat;
    case: "heartbeat";
  } | {
    /**
     * @generated from field: openarm.v1.SetJointAngles set_joint_angles = 11;
     */
    value: SetJointAngles;
    case: "setJointAngles";
  } | {
    /**
     * @generated from field: openarm.v1.Ack ack = 12;
     */
    value: Ack;
    case: "ack";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message openarm.v1.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export const MessageSchema: GenMessage<Message> = /*@__PURE__*/
  messageDesc(file_openarm_v1_messages, 0);

/**
 * @generated from message openarm.v1.Heartbeat
 */
export type Heartbeat = Message$1<"openarm.v1.Heartbeat"> & {
};

/**
 * Describes the message openarm.v1.Heartbeat.
 * Use `create(HeartbeatSchema)` to create a new message.
 */
export const HeartbeatSchema: GenMessage<Heartbeat> = /*@__PURE__*/
  messageDesc(file_openarm_v1_messages, 1);

/**
 * @generated from message openarm.v1.Ack
 */
export type Ack = Message$1<"openarm.v1.Ack"> & {
  /**
   * @generated from field: uint32 seq_ack = 1;
   */
  seqAck: number;

  /**
   * @generated from field: openarm.v1.Status status = 2;
   */
  status: Status;

  /**
   * @generated from field: string message = 3;
   */
  message: string;
};

/**
 * Describes the message openarm.v1.Ack.
 * Use `create(AckSchema)` to create a new message.
 */
export const AckSchema: GenMessage<Ack> = /*@__PURE__*/
  messageDesc(file_openarm_v1_messages, 2);

/**
 * @generated from message openarm.v1.SetJointAngles
 */
export type SetJointAngles = Message$1<"openarm.v1.SetJointAngles"> & {
  /**
   * @generated from field: float base_rad = 1;
   */
  baseRad: number;

  /**
   * @generated from field: float shoulder_rad = 2;
   */
  shoulderRad: number;

  /**
   * @generated from field: float elbow_rad = 3;
   */
  elbowRad: number;
};

/**
 * Describes the message openarm.v1.SetJointAngles.
 * Use `create(SetJointAnglesSchema)` to create a new message.
 */
export const SetJointAnglesSchema: GenMessage<SetJointAngles> = /*@__PURE__*/
  messageDesc(file_openarm_v1_messages, 3);

/**
 * @generated from enum openarm.v1.Status
 */
export enum Status {
  /**
   * @generated from enum value: STATUS_OK = 0;
   */
  OK = 0,

  /**
   * @generated from enum value: STATUS_INVALID = 1;
   */
  INVALID = 1,

  /**
   * @generated from enum value: STATUS_OUT_OF_RANGE = 2;
   */
  OUT_OF_RANGE = 2,

  /**
   * @generated from enum value: STATUS_TIMEOUT = 3;
   */
  TIMEOUT = 3,

  /**
   * @generated from enum value: STATUS_I2C_ERROR = 4;
   */
  I2C_ERROR = 4,

  /**
   * @generated from enum value: STATUS_EMERGENCY_STOP = 5;
   */
  EMERGENCY_STOP = 5,
}

/**
 * Describes the enum openarm.v1.Status.
 */
export const StatusSchema: GenEnum<Status> = /*@__PURE__*/
  enumDesc(file_openarm_v1_messages, 0);

