name: Deploy WebConnect to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/webconnect/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Build WebConnect
        run: cd apps/webconnect && bun run build
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: apps/webconnect/build
          cname: # Optional: add your custom domain here
